### ISSUE TITLE
Abstract for Textfield not matching Abstract

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-raylib#1]
I got this error
haxeui-raylib/git/haxe/ui/backend/raylib/TextField.hx:679: characters 36-50 : Abstract<KeyboardKey> has no field KEY_LEFT_SHIFT

I fixed it by changing code in Textfield to match the abstract.

This is from the abstract
 @:native("KEY_LEFT")                public static var LEFT:Int;

So I changed from KEY_LEFT_SHIFT to LEFT_SHIFT

Or something like that. anyways I created a patch file which I have never done before.

[patch.txt](https://github.com/haxeui/haxeui-raylib/files/6743790/patch.txt)

**Comment by ianharrigan** [comment]
Good point... i had that (and some other) changes locally... should be fixed in latest version
