### ISSUE TITLE
haxe.ui.core.Component has no field alpha

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-raylib#3]
from code layer.component.alpha = .4;

Let me know if you need a project. I assume this is known issue

**Comment by ianharrigan** [comment]
Nope, not known... will check it out.

Cheers,
Ian

**Comment by ianharrigan** [comment]
Where are you gettting "alpha" from? Did you mean "opacity"? I dont think "alpha" is a haxeui property is it?

**Comment by hoseyjoe** [comment]
Autocomplete was compiling to heaps.
component.alpha just worked.....sorry for the noise

Not sure how to avoid in the future. Maybe have and override on alpha. Anyways.  Closign
