### ISSUE TITLE
Enable file formats

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-raylib#4]
It appears jpg arent accepted by raylib but they can be by passing in defines?

Someone said You can build Raylib with support for JPG by changing the properties in config.h

**Comment by hoseyjoe** [comment]
"You can build Raylib with support for JPG by changing the properties in config.h" didnt work for me...idk

**Comment by ianharrigan** [comment]
OK, this should work now: 

![image](https://user-images.githubusercontent.com/3024242/143834715-6a00852e-b7d8-401d-aa0f-a0d794a55cfb.png)

(latest raylib-haxe and haxeui-raylib)

**Comment by hoseyjoe** [comment]
works for me
