### ISSUE TITLE
Resizing image doesnt work

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-raylib#5]
Setting height/width of Image does work in RayLib.  Same lines work in HL.  The monkey, in this case, loads but is not resized.  The image layers under other items so HaxeUI thinks of it as resized.  The code in question is in F2.hx

var layer = addImage("library/monkey.png", 6);
layer.component.width = 40;
layer.component.height = 40;

[project.zip](https://github.com/haxeui/haxeui-raylib/files/6870123/project.zip)

**Comment by ianharrigan** [comment]
This should be fixed now: 

![image](https://user-images.githubusercontent.com/3024242/143833171-fed3ad9a-cd41-4dc7-814a-2accef9d51be.png)

One of the benefits of generating the externs is you get all the functions now, which is nice :)

**Comment by hoseyjoe** [comment]
works for me
