### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-raylib#9]
I did 
haxe.exe --connect 6000 raylib.hxml 

and got
```
C:\SDKs\Haxe\haxe\lib\haxeui-raylib/git/haxe/ui/backend/AssetsImpl.hx:20: characters 73-74 : cpp.Pointer<cpp.UInt8> should be cpp.RawConstPointer<Int>
C:\SDKs\Haxe\haxe\lib\haxeui-raylib/git/haxe/ui/backend/AssetsImpl.hx:20: characters 73-74 : ... For function argument 'fileData'
The terminal process "C:\SDKs\Haxe\haxe\haxe.exe '--connect', '6000', 'raylib.hxml'" terminated with exit code: 1.
```

Let me know if we need more info. I not sure what is causing this as it ran before

**Comment by ianharrigan** [comment]
Nice catch, i wonder why i didnt get that error - maybe i didnt have a clean build. Either way, should be fixed now. You'll need latest haxeui-raylib and latest raylib-haxe.

Cheers,
Ian

**Comment by hoseyjoe** [comment]
works for me
